import { getTinyFishApiKey } from '../config';
import { SearchToolError, safeProviderCode } from './errors';
import { normalizeProviderResponse } from './normalize';
import type { NormalizedSearch, SearchInput, SearchKind } from './types';
export type TinyDeps={fetch?:typeof fetch;now?:()=>number;sleep?:(ms:number,signal?:AbortSignal)=>Promise<void>};
const endpoint='https://api.search.tinyfish.ai/'; const deadlineMs=10000;
export function buildTinyFishUrl(kind:SearchKind,input:SearchInput){const u=new URL(endpoint); const p=u.searchParams; p.set('query',input.query); p.set('domain_type',kind); for(const k of ['purpose','location','language','include_domains','exclude_domains','recency_minutes','after_date','before_date','page'] as const){const v=input[k]; if(v!==undefined)p.set(k,String(v));} return u}
export function retryAfter(v:string|null){if(!v||!/^[0-9]+$/.test(v))return undefined; const n=Number(v); return Number.isSafeInteger(n)?n:undefined}
export async function tinyFishSearch(kind:SearchKind,input:SearchInput,signal?:AbortSignal,deps:TinyDeps={},env:NodeJS.ProcessEnv=process.env):Promise<NormalizedSearch>{const key=getTinyFishApiKey(env); if(!key) throw new SearchToolError('CONFIGURATION_ERROR'); const f=deps.fetch??fetch, now=deps.now??(()=>Date.now()), sleep=deps.sleep??((ms,s)=>new Promise<void>((res,rej)=>{const t=setTimeout(res,ms); s?.addEventListener('abort',()=>{clearTimeout(t); rej(new DOMException('Aborted','AbortError'))},{once:true});})); const start=now(); let attempts=0; let last:SearchToolError|undefined; while(attempts<2){if(signal?.aborted) throw new SearchToolError('REQUEST_CANCELLED'); if(now()-start>=deadlineMs) throw new SearchToolError('UPSTREAM_TIMEOUT'); attempts++; const ctl=new AbortController(); const timeout=setTimeout(()=>ctl.abort(),Math.max(0,deadlineMs-(now()-start))); signal?.addEventListener('abort',()=>ctl.abort(),{once:true}); try{const res=await f(buildTinyFishUrl(kind,input),{method:'GET',headers:{'X-API-Key':key,Accept:'application/json'},cache:'no-store',signal:ctl.signal}); clearTimeout(timeout); if(res.ok)return await normalizeProviderResponse(res,input.query); if(res.status===429) throw new SearchToolError('UPSTREAM_RATE_LIMITED',undefined,retryAfter(res.headers.get('retry-after'))); if(res.status>=400&&res.status<500) throw new SearchToolError('UPSTREAM_REJECTED',safeProviderCode(await safeCode(res))); if(res.status===500||res.status===503){last=new SearchToolError('UPSTREAM_UNAVAILABLE');} else throw new SearchToolError('UPSTREAM_UNAVAILABLE'); }catch(e){clearTimeout(timeout); if(e instanceof SearchToolError && !['UPSTREAM_UNAVAILABLE'].includes(e.code)) throw e; if(signal?.aborted) throw new SearchToolError('REQUEST_CANCELLED'); last=new SearchToolError('UPSTREAM_UNAVAILABLE'); } if(attempts<2&&now()-start+250<deadlineMs) await sleep(250,signal); else break;} throw last??new SearchToolError('UPSTREAM_TIMEOUT')}
async function safeCode(res:Response){try{const t=await res.text(); const j=JSON.parse(t); return j?.error?.code??j?.code}catch{return undefined}}
